export const GO = 'https://amigo.geneontology.org/amigo/term/'
export const UNIPROTKB = 'https://www.uniprot.org/uniprotkb/'
export const CHEBI = 'http://purl.obolibrary.org/obo/CHEBI_'
export const UBERON = 'http://purl.obolibrary.org/obo/UBERON_'
export const CDPO = 'https://github.com/uermel/cdpo'

export const GO_PREFIX = 'GO:'
export const UNIPROTKB_PREFIX = 'UniProtKB:'
export const CHEBI_PREFIX = 'CHEBI:'
export const UBERON_PREFIX = 'UBERON:'
export const CDPO_PREFIX = 'CDPO:'
