export enum QueryParams {
  AuthorName = 'author',
  AuthorOrcid = 'author_orcid',
  AvailableFiles = 'files',
  CameraManufacturer = 'camera_manufacturer',
  Download = 'download',
  EmdbId = 'emdb_id',
  EmpiarId = 'empiar_id',
  FiducialAlignmentStatus = 'fiducial_alignment',
  GroundTruthAnnotation = 'ground_truth',
  NumberOfRuns = 'runs',
  ObjectName = 'object',
  ObjectShapeType = 'object_shape',
  Organism = 'organism',
  PortalId = 'portal_id',
  ReconstructionMethod = 'reconstruction_method',
  ReconstructionSoftware = 'reconstruction_software',
  TiltRangeMax = 'tilt_max',
  TiltRangeMin = 'tilt_min',
}
