export enum QueryParams {
  AnnotationId = 'annotation_id',
  AnnotationName = 'annotation_name',
  AnnotationSoftware = 'annotation-software',
  AnnotationsPage = 'annotations-page',
  AuthorName = 'author',
  AuthorOrcid = 'author_orcid',
  AvailableFiles = 'files',
  CameraManufacturer = 'camera_manufacturer',
  Competition = 'competition',
  DatasetId = 'dataset_id',
  DepositionId = 'deposition-id',
  DepositionTab = 'deposition-tab',
  DownloadConfig = 'download-config',
  DownloadStep = 'download-step',
  DownloadTab = 'download-tab',
  DownloadTomogramId = 'download-tomogram',
  EmdbId = 'emdb_id',
  EmpiarId = 'empiar_id',
  FiducialAlignmentStatus = 'fiducial_alignment',
  FileFormat = 'file-format',
  From = 'from',
  GroundTruthAnnotation = 'ground_truth',
  MetadataDrawer = 'metadata',
  MethodSummaryTab = 'method-summary-tab',
  MethodType = 'method-type',
  NumberOfRuns = 'runs',
  ObjectId = 'object-id',
  ObjectName = 'object',
  ObjectShapeType = 'object_shape',
  Organism = 'organism',
  Page = 'page',
  QualityScore = 'quality_score',
  ReconstructionMethod = 'reconstruction_method',
  ReconstructionSoftware = 'reconstruction_software',
  ReferenceTomogramId = 'ref-tomogram',
  Search = 'search',
  Sort = 'sort',
  Tab = 'tab',
  TableTab = 'table-tab',
  TiltRangeMax = 'tilt_max',
  TiltRangeMin = 'tilt_min',
  TomogramProcessing = 'tomogram-processing',
  TomogramSampling = 'tomogram-sampling',
  TomogramsPage = 'tomograms-page',
  EnableFeature = 'enable-feature',
  DisableFeature = 'disable-feature',
  GroupBy = 'group-by',
}

export enum FromLocationKey {
  OrganismAccordion = 'organism-accordion',
}
