version: '3.8'

services:
  data-portal:
    image: cryoet-data-portal/data-portal
    build:
      context: .
      dockerfile: packages/data-portal/Dockerfile
    ports:
      - 8080:8080

  graphiql:
    image: cryoet-data-portal/graphiql
    build:
      context: .
      dockerfile: packages/graphiql/Dockerfile
    ports:
      - 8081:80
