version: "3.8"
services:
  frontend:
    image: frontend
    platform: linux/amd64
    profiles:
    - '*'
    build:
      context: .
      dockerfile: packages/data-portal/Dockerfile
    healthcheck:
      test: timeout 1s bash -c ':> /dev/tcp/127.0.0.1/8080' || exit 1
    ports:
      - 8080:8080
