# Auto-generated by 'happy infra'. Do not edit
# Make improvements in happy, so that everyone can benefit.
provider "aws" {
  region = "us-west-2"
  assume_role {
    role_arn = "arn:aws:iam::${var.aws_account_id}:role/${var.aws_role}"
  }
  allowed_account_ids = ["${var.aws_account_id}"]
}
data "aws_eks_cluster" "cluster" {
  name = var.k8s_cluster_id
}
data "aws_eks_cluster_auth" "cluster" {
  name = var.k8s_cluster_id
}
provider "kubernetes" {
  host                   = data.aws_eks_cluster.cluster.endpoint
  cluster_ca_certificate = base64decode(data.aws_eks_cluster.cluster.certificate_authority.0.data)
  token                  = data.aws_eks_cluster_auth.cluster.token
}
data "kubernetes_namespace" "happy-namespace" {
  metadata {
    name = var.k8s_namespace
  }
}
provider "datadog" {
  validate = false
}
