# Validates PR title follows conventional commits
name: conventional commits check
on:
  pull_request:
    branches: main
    types:
      - edited
      - opened
      - synchronize
      - reopened

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  conventional_commit_title:
    runs-on: [ARM64, self-hosted, Linux]
    steps:
      - uses: chanzuckerberg/github-actions/.github/actions/conventional-commits@v2.1.0
