# Validates PR title follows conventional commits
name: conventional commits check
on:
  pull_request:
    branches: main
    types:
      - edited
      - opened
      - synchronize
      - reopened

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  conventional_commit_title:
    runs-on: [ARM64, self-hosted, Linux]
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
