name: Python cryoet_data_portal build

on:
  pull_request:
    paths:
      - "client/python/**"
      - ".github/workflows/**" # Re-run if a workflow is modified - useful to test workflow changes in PRs
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  publish-pypi-package:
    name: Build Python wheel and sdist, and publish to PyPI
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/cellxgene-ontology-guide
    permissions:
      id-token: write # IMPORTANT: this permission is mandatory for trusted publishing
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v4
        with:
          pyton-version: "3.10"
      - name: build
        run: |
          make build -C client/python/cryoet_data_portal
      - name: install
        run: |
          pip install ./client/python/cryoet_data_portal/dist/cryoet_data_portal-0.1.0-py3-none-any.whl
      - name: Publish distribution 📦 to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: client/python/cryoet_data_portal/dist
