name: Python cryoet_data_portal release

on:
  push:
    branches:
      - main
      - tsmith/automate-release

    paths:
      - 'client/python/cryoet_data_portal/**'
      - '.github/workflows/py-build.yml'
  workflow_dispatch:

concurrency:
  group: create-python-client-release
  cancel-in-progress: false

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: release please
        uses: googleapis/release-please-action@v4
        id: release
        with:
          manifest-file: "release-please.manifest.json"
          config-file: "release-please.config.json"
          target-branch: "tsmith/automate-release" # TODO change to main
