# write a Github actions to verify the workflow "Python Client Tests" on the main branch ran successfully.
name: Client Release Check
on:
  pull_request:
    branches:
      - release-please--branches--tsmith/automate-release--components--cryoet-data-portal-python-client
      - tsmith/automate-release
  push:
    branches:
      - release-please--branches--tsmith/automate-release--components--cryoet-data-portal-python-client
      - tsmith/automate-release

jobs:
  release-check:
    runs-on: ubuntu-latest
    steps:
      - name: check client tests on main
        uses: actions/github-script@v7
        with:
          retries: 10
          script: |
            const { data } = await github.actions.listForRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'main',
              check_name: 'Python Client Tests',
              filter: 'latest',
            });
            if (data.workflow_runs[0].conclusion !== 'success') {
              core.setFailed('Tests failed on main');
            }
